server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5  

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE


spring:
  application:
    name: gateway    


spring.cloud.gateway.routes:
- id: usuario_route
  uri: lb://USUARIO/
  predicates:
    - Path=/usuario/**
  filters:
    - StripPrefix=1
            
            
management:
  endpoints:
    web:
      exposure:
        include: "*"

    
app.eureka-server: localhost  
---
# spring.config.activate.on-profile: docker
# app.eureka-server: discovery
# eureka:
#   client:
#     serviceUrl:
#       defaultZone: http://discovery:8761/eureka/

